title: Lab Mãe D'Água
description: Laboratório Experimental de Ciência Cidadã, Cultura Oceânica e Tecnologia
theme: jekyll-theme-cayman
url: https://maedagua.github.io/maedagua.github.io/
sass:
  load_paths:
    - _sass
    - assets
